name: Deploy to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

    - name: Add Bitbucket remote
      run: |
        git remote add bitbucket git@bitbucket.org:mtheme1231/klwp-data.git

    - name: Push to Bitbucket
      run: |
        git push bitbucket main
